// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: grpc/categorization.proto

package grpcgo

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TextCategorizationInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextCategorizationInput) Reset() {
	*x = TextCategorizationInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_categorization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextCategorizationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCategorizationInput) ProtoMessage() {}

func (x *TextCategorizationInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_categorization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCategorizationInput.ProtoReflect.Descriptor instead.
func (*TextCategorizationInput) Descriptor() ([]byte, []int) {
	return file_grpc_categorization_proto_rawDescGZIP(), []int{0}
}

func (x *TextCategorizationInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextCategorizationOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text         string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PredictionId string `protobuf:"bytes,2,opt,name=prediction_id,json=predictionId,proto3" json:"prediction_id,omitempty"`
	Category     int32  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *TextCategorizationOutput) Reset() {
	*x = TextCategorizationOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_categorization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextCategorizationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCategorizationOutput) ProtoMessage() {}

func (x *TextCategorizationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_categorization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCategorizationOutput.ProtoReflect.Descriptor instead.
func (*TextCategorizationOutput) Descriptor() ([]byte, []int) {
	return file_grpc_categorization_proto_rawDescGZIP(), []int{1}
}

func (x *TextCategorizationOutput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextCategorizationOutput) GetPredictionId() string {
	if x != nil {
		return x.PredictionId
	}
	return ""
}

func (x *TextCategorizationOutput) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

var File_grpc_categorization_proto protoreflect.FileDescriptor

var file_grpc_categorization_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x17, 0x54,
	0x65, 0x78, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x6f, 0x0a, 0x18, 0x54, 0x65,
	0x78, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x7a, 0x0a, 0x12, 0x54,
	0x65, 0x78, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x64, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x64, 0x72, 0x6f, 0x64, 0x65, 0x6f, 0x6c, 0x69,
	0x76, 0x65, 0x69, 0x72, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_categorization_proto_rawDescOnce sync.Once
	file_grpc_categorization_proto_rawDescData = file_grpc_categorization_proto_rawDesc
)

func file_grpc_categorization_proto_rawDescGZIP() []byte {
	file_grpc_categorization_proto_rawDescOnce.Do(func() {
		file_grpc_categorization_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_categorization_proto_rawDescData)
	})
	return file_grpc_categorization_proto_rawDescData
}

var file_grpc_categorization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_categorization_proto_goTypes = []interface{}{
	(*TextCategorizationInput)(nil),  // 0: categorization.TextCategorizationInput
	(*TextCategorizationOutput)(nil), // 1: categorization.TextCategorizationOutput
}
var file_grpc_categorization_proto_depIdxs = []int32{
	0, // 0: categorization.TextCategorization.GetPrediction:input_type -> categorization.TextCategorizationInput
	1, // 1: categorization.TextCategorization.GetPrediction:output_type -> categorization.TextCategorizationOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_categorization_proto_init() }
func file_grpc_categorization_proto_init() {
	if File_grpc_categorization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_categorization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextCategorizationInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_categorization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextCategorizationOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_categorization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_categorization_proto_goTypes,
		DependencyIndexes: file_grpc_categorization_proto_depIdxs,
		MessageInfos:      file_grpc_categorization_proto_msgTypes,
	}.Build()
	File_grpc_categorization_proto = out.File
	file_grpc_categorization_proto_rawDesc = nil
	file_grpc_categorization_proto_goTypes = nil
	file_grpc_categorization_proto_depIdxs = nil
}
