apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 12
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: gcr.io/locust-rest-grpc/locust-rest-grpc
#          imagePullPolicy: Never
          resources:
            requests:
              memory: 0.2G
              cpu: 1
            limits:
              memory: 1G
              cpu: 2
          ports:
            - name: http-api
              containerPort: 80
          env:
            - name: MODULE_NAME
              value: "apis.fastapi.main"
            - name: MAX_WORKERS
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
#      nodeSelector:
#        workload: api
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http-api
