apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: gcr.io/locust-rest-grpc/locust-rest-grpc
          command: [ "locust", "-f", "locust_grpc.py", "--master"]
#          imagePullPolicy: Never
          resources:
            requests:
              memory: 0.2G
              cpu: .2
            limits:
              memory: 0.5G
              cpu: 1
          ports:
            - name: loc-master-ui
              containerPort: 8089
            - name: loc-master-p1
              containerPort: 5557
            - name: loc-master-p2
              containerPort: 5558
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust-master
  ports:
    - port: 8089
      targetPort: loc-master-ui
      name: loc-master-ui
    - port: 5557
      targetPort: loc-master-p1
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      name: loc-master-p2
  type: LoadBalancer
