# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: categorization.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='categorization.proto',
  package='categorization',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61tegorization.proto\x12\x0e\x63\x61tegorization\"\'\n\x17TextCategorizationInput\x12\x0c\n\x04text\x18\x02 \x01(\t\"Q\n\x18TextCategorizationOutput\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rprediction_id\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\x05\x32z\n\x12TextCategorization\x12\x64\n\rGetPrediction\x12\'.categorization.TextCategorizationInput\x1a(.categorization.TextCategorizationOutput\"\x00\x62\x06proto3'
)




_TEXTCATEGORIZATIONINPUT = _descriptor.Descriptor(
  name='TextCategorizationInput',
  full_name='categorization.TextCategorizationInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='categorization.TextCategorizationInput.text', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=79,
)


_TEXTCATEGORIZATIONOUTPUT = _descriptor.Descriptor(
  name='TextCategorizationOutput',
  full_name='categorization.TextCategorizationOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='categorization.TextCategorizationOutput.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prediction_id', full_name='categorization.TextCategorizationOutput.prediction_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='categorization.TextCategorizationOutput.category', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['TextCategorizationInput'] = _TEXTCATEGORIZATIONINPUT
DESCRIPTOR.message_types_by_name['TextCategorizationOutput'] = _TEXTCATEGORIZATIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextCategorizationInput = _reflection.GeneratedProtocolMessageType('TextCategorizationInput', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCATEGORIZATIONINPUT,
  '__module__' : 'categorization_pb2'
  # @@protoc_insertion_point(class_scope:categorization.TextCategorizationInput)
  })
_sym_db.RegisterMessage(TextCategorizationInput)

TextCategorizationOutput = _reflection.GeneratedProtocolMessageType('TextCategorizationOutput', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCATEGORIZATIONOUTPUT,
  '__module__' : 'categorization_pb2'
  # @@protoc_insertion_point(class_scope:categorization.TextCategorizationOutput)
  })
_sym_db.RegisterMessage(TextCategorizationOutput)



_TEXTCATEGORIZATION = _descriptor.ServiceDescriptor(
  name='TextCategorization',
  full_name='categorization.TextCategorization',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=164,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrediction',
    full_name='categorization.TextCategorization.GetPrediction',
    index=0,
    containing_service=None,
    input_type=_TEXTCATEGORIZATIONINPUT,
    output_type=_TEXTCATEGORIZATIONOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTCATEGORIZATION)

DESCRIPTOR.services_by_name['TextCategorization'] = _TEXTCATEGORIZATION

# @@protoc_insertion_point(module_scope)
