# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import categorization_pb2 as categorization__pb2


class TextCategorizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrediction = channel.unary_unary(
                '/categorization.TextCategorization/GetPrediction',
                request_serializer=categorization__pb2.TextCategorizationInput.SerializeToString,
                response_deserializer=categorization__pb2.TextCategorizationOutput.FromString,
                )


class TextCategorizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextCategorizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrediction,
                    request_deserializer=categorization__pb2.TextCategorizationInput.FromString,
                    response_serializer=categorization__pb2.TextCategorizationOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'categorization.TextCategorization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextCategorization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/categorization.TextCategorization/GetPrediction',
            categorization__pb2.TextCategorizationInput.SerializeToString,
            categorization__pb2.TextCategorizationOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
